name: gofish
channels:
  - conda-forge
  - nodefaults
dependencies:
  # basic
  - python=3.10
  - typing_extensions>=4.7.1,<5.0
  - black=24.2.0
  - numpy>=1.21.0
  - scipy>=1.7
  - pandas>=1.3.0
  - matplotlib>=3.6.0
  - configobj
  - findiff
  - quadpy==0.16.10
  # cosmo
  - camb>=1.5.0
  # pypower
  - sympy
  - numexpr
  # miscellaneous
  - ipython
  - ipykernel
  # pip
  - pip
